### ISSUE TITLE
let's in index.js produces build errors in Vue + Webpack projects.

### ISSUE THREAD

**Issue by alexcheninfo** [igor-ribeiro/calendar-js#13]
This is the error that shows up if you do `npm run build`:

```
ERROR in static/js/vendor.a6271913414e87e123c2.js from UglifyJs
Unexpected token: name (_months) [./node_modules/calendar-js/index.js:56,0][static/js/vendor.a6271913414e87e123c2.js:90602,6]
```
Vue + Webpack doesn't like the `let`'s in the index.js of this project (the const's are okay).

I believe the current version of UglifyJS that Webpack has doesn't play well with ES6.

I wonder if you could replace the `let`'s in index.js with `var`'s? That would save my project for this month!

(Some say that this issue with UglifyJS will be solved in Webpack 4.)

**Comment by igor-ribeiro** [comment]
Hi!

I looks like an issue with UglifyJS as you said: https://github.com/mishoo/UglifyJS2/issues/887.

I will go back to using `var`. Thanks for the issue.
