### ISSUE TITLE
bug in using 0 index for month in calendar().of(year, month)

### ISSUE THREAD

**Issue by luki06** [igor-ribeiro/calendar-js#20]
hi,
i use 0 index to January but it throw error .
![error](https://user-images.githubusercontent.com/45301056/48962906-c2082980-ef7f-11e8-8103-6c080083c973.PNG)
 As you can see on top the variable is 0 ,all other number work except index 0,thanks.

**Comment by igor-ribeiro** [comment]
I don't get it, can you explain more? Put the code also.

**Comment by luki06** [comment]
hi thanks for your response ,here is my code
![capture](https://user-images.githubusercontent.com/45301056/49441958-f1106d80-f7bf-11e8-84ce-f91b4363be3c.PNG)
year and month are parameter of function called calender_api
![capture1](https://user-images.githubusercontent.com/45301056/49442042-2ddc6480-f7c0-11e8-9763-0f526f70f897.PNG)
it seem i get error when monthis at 0 or 11
![capture2](https://user-images.githubusercontent.com/45301056/49442112-62e8b700-f7c0-11e8-90c4-f3a99f910d87.PNG)
as you can see in the second console log it give 11 for month and still i get error
thanks.

**Comment by luki06** [comment]
i am sorry it was a bug in my code i did fixed it thanks

**Comment by igor-ribeiro** [comment]
No problems! Im glad that you found out.
Thanks!
