### ISSUE TITLE
Disable certain days of the week

### ISSUE THREAD

**Issue by ArmandoAmador** [igor-ribeiro/calendar-js#29]
Hi, awesome lib!

I was wondering is there a way to disable certain days of the week for every week. I'm thinking whether it's a holiday or the business doesn't operate let's say on Tuesday and Thursday, how can I go about disabling those days in this lib?

Thank you in advance

**Comment by igor-ribeiro** [comment]
Hey @ArmandoAmador ! Thanks for the compliment.

You can achieve that with the transformer, the third argument to `.detailed()`

**Comment by ArmandoAmador** [comment]
I meant to update my response here that I had figured out how to do it with the transformer. Once again @igor-ribeiro thank you for your hard work providing us with this cool lib!
