### ISSUE TITLE
a function to validate date

### ISSUE THREAD

**Issue by jemhuntr** [igor-ribeiro/calendar-js#8]
Hi! First of all thank you for this really easy to use calendar generator. Much much much more flexible rather than having to use other libraries that generate markup for me.

It would, however, be great if there was a function to validate whether a given date is valid (say, if I input Feb 29, 2017, it should return false).

Would this feature be in your roadmap? Thanks!

**Comment by igor-ribeiro** [comment]
Thank you soooo much for the compliments!

You want something like this `calendar.validate('Feb 29, 2017')`?

**Comment by jemhuntr** [comment]
hmm, I was thinking just a simple function like `calendar.validate(2017, 0, 5)` which would return true whereas `calendar.validate(2017, 1, 29)` would return false as 2017 isn't a leap year (so that date doesn't exist).

Number inputs might make more sense as that is how `.of()` works.

**Comment by igor-ribeiro** [comment]
Sorry for the delay, I'll add it since it's looks trivial to add.
