### ISSUE TITLE
dealing with zero-index vs one-index of month

### ISSUE THREAD

**Issue by jemhuntr** [igor-ribeiro/calendar-js#9]
This may be entirely based on the dataset we're working with, but in my case, one-indexed months seem much more intuitive (as this is what I immediately pass to other spec-compliant services).

[ISO-8601](https://www.w3.org/TR/NOTE-datetime) also lists months as one-indexed, (01 - January, 02 - February, ... , 12 - December). Would it be possible to switch to using this system from the zero-indexed format calendarJS is currently using?

Edit: Stupid me, I just realized JavaScript is using zero-indexed months. Guess I'll have to handle this manually then :(

Would be great if there was some other way to deal with this more elegantly.

**Comment by igor-ribeiro** [comment]
In programming everything starts in zero, but I can add a config option for this.

**Comment by jemhuntr** [comment]
I can live without this option as I already am handling this inconsistency manually. Would be a great addition though.

**Comment by igor-ribeiro** [comment]
i'm closing since this is the default behavior.
